modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Potion-Studios/Potion-Studios-Oh-The-Biomes-Weve-Gone/issues"
license = "All Rights Reserved"

[[mods]]
modId = "biomeswevegone"
version = "${version}"
displayName = "Oh The Biomes We've Gone"
logoFile="OTBWG.png"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL, YaBoiChips, Corgi Taco"
description = '''
Sequel to Oh The Biomes You'll Go, this mod adds a variety of new biomes to the game.
'''
displayURL="https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone"

[[dependencies.biomeswevegone]]
modId = "forge"
mandatory = true
versionRange = "[47.1.101,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "terrablender"
mandatory = true
versionRange = "[3.0.1.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "corgilib"
mandatory = true
versionRange = "[4.0.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "ohthetreesyoullgrow"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4,)"
ordering = "AFTER"
side = "BOTH"
