modLoader = "javafml"
loaderVersion = "[52,)"
issueTrackerURL = "https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues"
license = "All Rights Reserved"

[[mods]]
modId = "biomeswevegone"
version = "${version}"
displayName = "Oh The Biomes We've Gone"
logoFile="OTBWG.png"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL, YaBoiChips, Corgi Taco"
description = '''
Sequel to Oh The Biomes You'll Go, this mod adds a variety of new biomes to the game.
'''
displayURL="https://potionstudios.net/"

[[dependencies.biomeswevegone]]
modId = "forge"
mandatory = true
versionRange = "[52.0.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "terrablender"
mandatory = true
versionRange = "[4.1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "corgilib"
mandatory = true
versionRange = "[5.0.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "ohthetreesyoullgrow"
mandatory = true
versionRange = "[5.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "geckolib"
mandatory = true
versionRange = "[4.6,)"
ordering = "AFTER"
side = "BOTH"
